services:
  checkbag-b2b:
    container_name: checkbag-b2b
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped